# Socio-Economic Status (SES) scores

In [76]:
import pandas as pd
import glob

files = glob.glob("../1_Data_raw/SES_WOA scores/*.csv")

dfs = []
#1. appending data-sets of 2014 until 2023
for f in files:
    df = pd.read_csv(f, sep=";")
    dfs.append(df)

ses = pd.concat(dfs, ignore_index=True)

In [77]:
ses.columns

Index(['ID', 'WijkenEnBuurten', 'Perioden', 'RegiocodeGemeenteWijkBuurt_1',
       'ParticuliereHuishoudens_2', 'k_1eTotEnMet40ePercentielgroep_3',
       'k_41eTotEnMet80ePercentielgroep_4',
       'k_81eTotEnMet100ePercentielgroep_5', 'GemiddeldePercentielgroep_6',
       'k_1eTotEnMet40ePercentielgroep_7', 'k_41eTotEnMet80ePercentielgroep_8',
       'k_81eTotEnMet100ePercentielgroep_9', 'GemiddeldePercentielgroep_10',
       'k_1eTotEnMet40ePercentielgroep_11',
       'k_41eTotEnMet80ePercentielgroep_12',
       'k_81eTotEnMet100ePercentielgroep_13', 'GemiddeldePercentielgroep_14',
       'Ondergrens95Interval_15', 'Waarde_16', 'Bovengrens95Interval_17',
       'Ondergrens95Interval_18', 'Waarde_19', 'Bovengrens95Interval_20',
       'Ondergrens95Interval_21', 'Waarde_22', 'Bovengrens95Interval_23',
       'Afgelopen4JaarVoortdurendWerkzaam_24',
       'Afgelopen4JrNietVoortdurendWerkzaam_25',
       'Afgelopen4JaarNietWerkzaam_26', 'Gepensioneerd_27',
       'Ondergrens95Interval_28', 'GemiddeldeScore_29',
       'Bovengrens95Interval_30', 'GemiddeldeScore_31',
       'Ondergrens95Interval_32', 'GemiddeldeScore_33',
       'Bovengrens95Interval_34', 'GemiddeldeScore_35',
       'Ondergrens95Interval_36', 'Waarde_37', 'Bovengrens95Interval_38',
       'Waarde_39', 'Ondergrens95Interval_40', 'Waarde_41',
       'Bovengrens95Interval_42', 'Waarde_43'],
      dtype='str')

In [78]:
#checking missing values

print("Columns:", ses.columns.tolist())
print("\nDatatypes:\n", ses.dtypes)
print("\nMissing values:\n", ses.isna().sum())
print("\nGM/WK/BU structure:\n", ses["WijkenEnBuurten"].str[:2].value_counts())
print("\nSES columns:\n", [c for c in ses.columns if "GemiddeldeScore" in c])
print("\nrows per year:\n", ses.groupby(ses["Perioden"].str[:4]).size())
print("\nmunicipalities per year:\n", ses.groupby(ses["Perioden"].str[:4])["WijkenEnBuurten"].nunique())

Columns: ['ID', 'WijkenEnBuurten', 'Perioden', 'RegiocodeGemeenteWijkBuurt_1', 'ParticuliereHuishoudens_2', 'k_1eTotEnMet40ePercentielgroep_3', 'k_41eTotEnMet80ePercentielgroep_4', 'k_81eTotEnMet100ePercentielgroep_5', 'GemiddeldePercentielgroep_6', 'k_1eTotEnMet40ePercentielgroep_7', 'k_41eTotEnMet80ePercentielgroep_8', 'k_81eTotEnMet100ePercentielgroep_9', 'GemiddeldePercentielgroep_10', 'k_1eTotEnMet40ePercentielgroep_11', 'k_41eTotEnMet80ePercentielgroep_12', 'k_81eTotEnMet100ePercentielgroep_13', 'GemiddeldePercentielgroep_14', 'Ondergrens95Interval_15', 'Waarde_16', 'Bovengrens95Interval_17', 'Ondergrens95Interval_18', 'Waarde_19', 'Bovengrens95Interval_20', 'Ondergrens95Interval_21', 'Waarde_22', 'Bovengrens95Interval_23', 'Afgelopen4JaarVoortdurendWerkzaam_24', 'Afgelopen4JrNietVoortdurendWerkzaam_25', 'Afgelopen4JaarNietWerkzaam_26', 'Gepensioneerd_27', 'Ondergrens95Interval_28', 'GemiddeldeScore_29', 'Bovengrens95Interval_30', 'GemiddeldeScore_31', 'Ondergrens95Interval_32', 'GemiddeldeScore_33', 'Bovengrens95Interval_34', 'GemiddeldeScore_35', 'Ondergrens95Interval_36', 'Waarde_37', 'Bovengrens95Interval_38', 'Waarde_39', 'Ondergrens95Interval_40', 'Waarde_41', 'Bovengrens95Interval_42', 'Waarde_43']

Datatypes:
 ID                                          int64
WijkenEnBuurten                               str
Perioden                                      str
RegiocodeGemeenteWijkBuurt_1                  str
ParticuliereHuishoudens_2                   int64
k_1eTotEnMet40ePercentielgroep_3          float64
k_41eTotEnMet80ePercentielgroep_4         float64
k_81eTotEnMet100ePercentielgroep_5        float64
GemiddeldePercentielgroep_6               float64
k_1eTotEnMet40ePercentielgroep_7          float64
k_41eTotEnMet80ePercentielgroep_8         float64
k_81eTotEnMet100ePercentielgroep_9        float64
GemiddeldePercentielgroep_10              float64
k_1eTotEnMet40ePercentielgroep_11         float64
k_41eTotEnMet80ePercentielgroep_12        float64
k_81eTotEnMet100ePercentielgroep_13       float64
GemiddeldePercentielgroep_14              float64
Ondergrens95Interval_15                   float64
Waarde_16                                 float64
Bovengrens95Interval_17                   float64
Ondergrens95Interval_18                   float64
Waarde_19                                 float64
Bovengrens95Interval_20                   float64
Ondergrens95Interval_21                   float64
Waarde_22                                 float64
Bovengrens95Interval_23                   float64
Afgelopen4JaarVoortdurendWerkzaam_24      float64
Afgelopen4JrNietVoortdurendWerkzaam_25    float64
Afgelopen4JaarNietWerkzaam_26             float64
Gepensioneerd_27                          float64
Ondergrens95Interval_28                   float64
GemiddeldeScore_29                        float64
Bovengrens95Interval_30                   float64
GemiddeldeScore_31                        float64
Ondergrens95Interval_32                   float64
GemiddeldeScore_33                        float64
Bovengrens95Interval_34                   float64
GemiddeldeScore_35                        float64
Ondergrens95Interval_36                   float64
Waarde_37                                 float64
Bovengrens95Interval_38                   float64
Waarde_39                                 float64
Ondergrens95Interval_40                   float64
Waarde_41                                 float64
Bovengrens95Interval_42                   float64
Waarde_43                                 float64
dtype: object

Missing values:
 ID                                            0
WijkenEnBuurten                               0
Perioden                                      0
RegiocodeGemeenteWijkBuurt_1                  0
ParticuliereHuishoudens_2                     0
k_1eTotEnMet40ePercentielgroep_3          49168
k_41eTotEnMet80ePercentielgroep_4         49168
k_81eTotEnMet100ePercentielgroep_5        49168
GemiddeldePercentielgroep_6               49168
k_1eTotEnMet40ePercentielgroep_7          49168
k_41eTotEnMet80ePercentielgroep_8         49168
k_81eTotEnMet100ePercentielgroep_9        49168
GemiddeldePercentielgroep_10              49168
k_1eTotEnMet40ePercentielgroep_11         49168
k_41eTotEnMet80ePercentielgroep_12        49168
k_81eTotEnMet100ePercentielgroep_13       49168
GemiddeldePercentielgroep_14              49168
Ondergrens95Interval_15                   49168
Waarde_16                                 49168
Bovengrens95Interval_17                   49168
Ondergrens95Interval_18                   49168
Waarde_19                                 49168
Bovengrens95Interval_20                   49168
Ondergrens95Interval_21                   49168
Waarde_22                                 49168
Bovengrens95Interval_23                   49168
Afgelopen4JaarVoortdurendWerkzaam_24      49168
Afgelopen4JrNietVoortdurendWerkzaam_25    49168
Afgelopen4JaarNietWerkzaam_26             49168
Gepensioneerd_27                          49168
Ondergrens95Interval_28                   49168
GemiddeldeScore_29                        49168
Bovengrens95Interval_30                   49168
GemiddeldeScore_31                        49168
Ondergrens95Interval_32                   49168
GemiddeldeScore_33                        49168
Bovengrens95Interval_34                   49168
GemiddeldeScore_35                        49168
Ondergrens95Interval_36                   49168
Waarde_37                                 49168
Bovengrens95Interval_38                   49168
Waarde_39                                 49168
Ondergrens95Interval_40                   49168
Waarde_41                                 49168
Bovengrens95Interval_42                   49168
Waarde_43                                 49168
dtype: int64

GM/WK/BU structure:
 WijkenEnBuurten
BU    145740
WK     33930
GM      3420
Name: count, dtype: int64

SES columns:
 ['GemiddeldeScore_29', 'GemiddeldeScore_31', 'GemiddeldeScore_33', 'GemiddeldeScore_35']

rows per year:
 Perioden
2014    18309
2015    18309
2016    18309
2017    18309
2018    18309
2019    18309
2020    18309
2021    18309
2022    18309
2023    18309
dtype: int64

municipalities per year:
 Perioden
2014    18309
2015    18309
2016    18309
2017    18309
2018    18309
2019    18309
2020    18309
2021    18309
2022    18309
2023    18309
Name: WijkenEnBuurten, dtype: int64

In [79]:
# filter municipalities
ses_gm = ses[ses["WijkenEnBuurten"].str.startswith("GM")]

# extrapolate Year (jaar) out of the column 'Perioden'
ses_gm["Jaar"]= ses_gm["Perioden"].str[:4].astype(int)

# Select SES-scores ("GemiddeldeScore_29)
ses_gm["SES_score"] = ses_gm["GemiddeldeScore_29"]

# Clean municipality codes
ses_gm["GemeenteCode"]= ses_gm["WijkenEnBuurten"].str[2:].astype(int)


ses_gm.head()

,ID,WijkenEnBuurten,Perioden,RegiocodeGemeenteWijkBuurt_1,ParticuliereHuishoudens_2,k_1eTotEnMet40ePercentielgroep_3,k_41eTotEnMet80ePercentielgroep_4,k_81eTotEnMet100ePercentielgroep_5,GemiddeldePercentielgroep_6,k_1eTotEnMet40ePercentielgroep_7,...,Waarde_37,Bovengrens95Interval_38,Waarde_39,Ondergrens95Interval_40,Waarde_41,Bovengrens95Interval_42,Waarde_43,Jaar,SES_score,GemeenteCode
0,0,GM1680,2014JJ00,GM1680,10900,28.5,44.6,26.9,58.1,32.6,...,0.701,0.703,0.321,0.279,0.282,0.285,0.265,2014,0.141,1680
76,760,GM0358,2014JJ00,GM0358,12400,26.8,43.5,29.7,60.1,28.1,...,0.677,0.680,0.310,0.285,0.289,0.292,0.234,2014,0.204,358
89,890,GM0197,2014JJ00,GM0197,11200,34.4,48.3,17.4,52.8,37.4,...,0.682,0.686,0.317,0.277,0.281,0.286,0.248,2014,0.085,197
123,1230,GM0059,2014JJ00,GM0059,11500,43.9,43.4,12.7,46.5,47.8,...,0.783,0.786,0.369,0.278,0.281,0.284,0.308,2014,-0.073,59
151,1510,GM0482,2014JJ00,GM0482,8000,38.8,43.4,17.8,51.3,38.1,...,0.758,0.763,0.343,0.293,0.297,0.301,0.273,2014,0.045,482

In [81]:
# Only keep the useful columns
ses_gm_clean = ses_gm[["GemeenteCode","Jaar", "SES_score"]].copy()
ses_gm_clean.head()

     GemeenteCode  Jaar  SES_score
0            1680  2014      0.141
76            358  2014      0.204
89            197  2014      0.085
123            59  2014     -0.073
151           482  2014      0.045

In [82]:
# Check for municipality code of "Haaren" which was split in 2021, if there is no output, the dataset has taken splitting and merging of municipalities taken into account
ses_gm_clean[ses_gm["GemeenteCode"] == 788].groupby("Jaar").size()

ses_gm_clean.groupby("Jaar")["GemeenteCode"].nunique()

Jaar
2014    342
2015    342
2016    342
2017    342
2018    342
2019    342
2020    342
2021    342
2022    342
2023    342
Name: GemeenteCode, dtype: int64

In [83]:
#sorting the ses_scores in the same format as the 'leegstandsmonitor'
ses_sorted = ses_gm_clean.sort_values(["Jaar", "GemeenteCode"], ascending=[False, True])
ses_sorted.head()

        GemeenteCode  Jaar  SES_score
171160            14  2023     -0.199
165164            34  2023      0.086
178836            37  2023     -0.150
180396            47  2023     -0.101
182568            50  2023      0.183

In [102]:
# SES scores to data_intermediate
ses_sorted.to_csv("../2_Data_intermediate/ses_woa_clean.csv", index=False)

pd.read_csv("../2_Data_intermediate/ses_woa_clean.csv")

      GemeenteCode  Jaar  SES_score
0               14  2023     -0.199
1               34  2023      0.086
2               37  2023     -0.150
3               47  2023     -0.101
4               50  2023      0.183
...            ...   ...        ...
3415          1979  2014     -0.088
3416          1980  2014      0.125
3417          1982  2014      0.120
3418          1991  2014      0.099
3419          1992  2014      0.121

[3420 rows x 3 columns]

# Population density per Municipality